# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/robin/Master/AI/DetectionContour

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/robin/Master/AI/DetectionContour

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/robin/Master/AI/DetectionContour/CMakeFiles /home/robin/Master/AI/DetectionContour/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/robin/Master/AI/DetectionContour/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TP1.exe

# Build rule for target.
TP1.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TP1.exe
.PHONY : TP1.exe

# fast build rule for target.
TP1.exe/fast:
	$(MAKE) -f CMakeFiles/TP1.exe.dir/build.make CMakeFiles/TP1.exe.dir/build
.PHONY : TP1.exe/fast

#=============================================================================
# Target rules for targets named OpenCvImgDisplay.exe

# Build rule for target.
OpenCvImgDisplay.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OpenCvImgDisplay.exe
.PHONY : OpenCvImgDisplay.exe

# fast build rule for target.
OpenCvImgDisplay.exe/fast:
	$(MAKE) -f CMakeFiles/OpenCvImgDisplay.exe.dir/build.make CMakeFiles/OpenCvImgDisplay.exe.dir/build
.PHONY : OpenCvImgDisplay.exe/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/TP1.exe.dir/build.make CMakeFiles/TP1.exe.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/TP1.exe.dir/build.make CMakeFiles/TP1.exe.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/TP1.exe.dir/build.make CMakeFiles/TP1.exe.dir/main.cpp.s
.PHONY : main.cpp.s

src/Computations.o: src/Computations.cpp.o

.PHONY : src/Computations.o

# target to build an object file
src/Computations.cpp.o:
	$(MAKE) -f CMakeFiles/TP1.exe.dir/build.make CMakeFiles/TP1.exe.dir/src/Computations.cpp.o
.PHONY : src/Computations.cpp.o

src/Computations.i: src/Computations.cpp.i

.PHONY : src/Computations.i

# target to preprocess a source file
src/Computations.cpp.i:
	$(MAKE) -f CMakeFiles/TP1.exe.dir/build.make CMakeFiles/TP1.exe.dir/src/Computations.cpp.i
.PHONY : src/Computations.cpp.i

src/Computations.s: src/Computations.cpp.s

.PHONY : src/Computations.s

# target to generate assembly for a file
src/Computations.cpp.s:
	$(MAKE) -f CMakeFiles/TP1.exe.dir/build.make CMakeFiles/TP1.exe.dir/src/Computations.cpp.s
.PHONY : src/Computations.cpp.s

src/imageDisplay.o: src/imageDisplay.cpp.o

.PHONY : src/imageDisplay.o

# target to build an object file
src/imageDisplay.cpp.o:
	$(MAKE) -f CMakeFiles/OpenCvImgDisplay.exe.dir/build.make CMakeFiles/OpenCvImgDisplay.exe.dir/src/imageDisplay.cpp.o
.PHONY : src/imageDisplay.cpp.o

src/imageDisplay.i: src/imageDisplay.cpp.i

.PHONY : src/imageDisplay.i

# target to preprocess a source file
src/imageDisplay.cpp.i:
	$(MAKE) -f CMakeFiles/OpenCvImgDisplay.exe.dir/build.make CMakeFiles/OpenCvImgDisplay.exe.dir/src/imageDisplay.cpp.i
.PHONY : src/imageDisplay.cpp.i

src/imageDisplay.s: src/imageDisplay.cpp.s

.PHONY : src/imageDisplay.s

# target to generate assembly for a file
src/imageDisplay.cpp.s:
	$(MAKE) -f CMakeFiles/OpenCvImgDisplay.exe.dir/build.make CMakeFiles/OpenCvImgDisplay.exe.dir/src/imageDisplay.cpp.s
.PHONY : src/imageDisplay.cpp.s

src/utils/Matrix.o: src/utils/Matrix.cpp.o

.PHONY : src/utils/Matrix.o

# target to build an object file
src/utils/Matrix.cpp.o:
	$(MAKE) -f CMakeFiles/TP1.exe.dir/build.make CMakeFiles/TP1.exe.dir/src/utils/Matrix.cpp.o
.PHONY : src/utils/Matrix.cpp.o

src/utils/Matrix.i: src/utils/Matrix.cpp.i

.PHONY : src/utils/Matrix.i

# target to preprocess a source file
src/utils/Matrix.cpp.i:
	$(MAKE) -f CMakeFiles/TP1.exe.dir/build.make CMakeFiles/TP1.exe.dir/src/utils/Matrix.cpp.i
.PHONY : src/utils/Matrix.cpp.i

src/utils/Matrix.s: src/utils/Matrix.cpp.s

.PHONY : src/utils/Matrix.s

# target to generate assembly for a file
src/utils/Matrix.cpp.s:
	$(MAKE) -f CMakeFiles/TP1.exe.dir/build.make CMakeFiles/TP1.exe.dir/src/utils/Matrix.cpp.s
.PHONY : src/utils/Matrix.cpp.s

src/utils/MatrixFilter.o: src/utils/MatrixFilter.cpp.o

.PHONY : src/utils/MatrixFilter.o

# target to build an object file
src/utils/MatrixFilter.cpp.o:
	$(MAKE) -f CMakeFiles/TP1.exe.dir/build.make CMakeFiles/TP1.exe.dir/src/utils/MatrixFilter.cpp.o
.PHONY : src/utils/MatrixFilter.cpp.o

src/utils/MatrixFilter.i: src/utils/MatrixFilter.cpp.i

.PHONY : src/utils/MatrixFilter.i

# target to preprocess a source file
src/utils/MatrixFilter.cpp.i:
	$(MAKE) -f CMakeFiles/TP1.exe.dir/build.make CMakeFiles/TP1.exe.dir/src/utils/MatrixFilter.cpp.i
.PHONY : src/utils/MatrixFilter.cpp.i

src/utils/MatrixFilter.s: src/utils/MatrixFilter.cpp.s

.PHONY : src/utils/MatrixFilter.s

# target to generate assembly for a file
src/utils/MatrixFilter.cpp.s:
	$(MAKE) -f CMakeFiles/TP1.exe.dir/build.make CMakeFiles/TP1.exe.dir/src/utils/MatrixFilter.cpp.s
.PHONY : src/utils/MatrixFilter.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... TP1.exe"
	@echo "... OpenCvImgDisplay.exe"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/Computations.o"
	@echo "... src/Computations.i"
	@echo "... src/Computations.s"
	@echo "... src/imageDisplay.o"
	@echo "... src/imageDisplay.i"
	@echo "... src/imageDisplay.s"
	@echo "... src/utils/Matrix.o"
	@echo "... src/utils/Matrix.i"
	@echo "... src/utils/Matrix.s"
	@echo "... src/utils/MatrixFilter.o"
	@echo "... src/utils/MatrixFilter.i"
	@echo "... src/utils/MatrixFilter.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

